### ISSUE TITLE
خطا در اجرا

### ISSUE THREAD

**Issue by fakhravari** [codehaks/BookShop#2]
با سلام
آیا این پروژه بعد از دریافت قابل اجرا است؟ چون یک سری خطا داره

![Untitled](https://github.com/codehaks/BookShop/assets/4311975/3f4d8b8e-b7aa-4695-86eb-46f484af63ec)

![Untitled](https://github.com/codehaks/BookShop/assets/4311975/4eb946fa-f6c8-4028-847c-4b9a17930f58)

**Comment by codehaks** [comment]
مشکل حل شد. 

توضیحات بیشتر در این ویدیو:
https://www.aparat.com/v/tdaVX
