### ISSUE TITLE
vs-threading.LegacyThreadSwitchingMembers.txt

### ISSUE THREAD

**Issue by fakhravari** [codehaks/BookShop#3]
با سلام
روی پروژه خودم موارد انجام دادم ، این موارد ها در سلوشن دیده میشه اما فایلی در پروژه برای این ها نمیبینم!
دقیقا چی هستن و چطور میشه حذفشون کرد

![Screenshot 2023-05-14 093057](https://github.com/codehaks/BookShop/assets/4311975/22a998f0-f179-4448-b14f-f69278c6d40d)

محتوای متنی
![Screenshot 2023-05-14 093057](https://github.com/codehaks/BookShop/assets/4311975/daf81be2-9678-4f72-bf45-93edd5be46a1)

**Comment by codehaks** [comment]
این فایل توسط تحلیگر کد ایجاد میشه: 

https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/configuration.md

**Comment by codehaks** [comment]
فایل در کتابخانه vs-threading قرار داره. این کتابخانه چندین تحلیل برای Threading در ویژوال استودیو فراهم می‌کند.

 فایل `vs-threading.LegacyThreadSwitchingMembers.txt` حاوی روش های کهنه Threading است که باید از آن‌ها خودداری شود. به جای آن، باید از `JoinableTaskFactory.SwitchToMainThreadAsync()` به عنوان روش استاندارد برای تغییر به رشته اصلی استفاده شود.
 
 این فایل تنظیمات است که میگه چه روشهایی نباید استفاده شود و جایگزینش باید چی باشد. 


امیدوارم کمک کرده باشم. اگر سوال دیگری دارید، به من بگوید.

**Comment by fakhravari** [comment]
> فایل در کتابخانه vs-threading قرار داره. این کتابخانه چندین تحلیل برای Threading در ویژوال استودیو فراهم می‌کند.
> 
> فایل `vs-threading.LegacyThreadSwitchingMembers.txt` حاوی روش های کهنه Threading است که باید از آن‌ها خودداری شود. به جای آن، باید از `JoinableTaskFactory.SwitchToMainThreadAsync()` به عنوان روش استاندارد برای تغییر به رشته اصلی استفاده شود.
> 
> این فایل تنظیمات است که میگه چه روشهایی نباید استفاده شود و جایگزینش باید چی باشد.
> 
> امیدوارم کمک کرده باشم. اگر سوال دیگری دارید، به من بگوید.


ممنون، یکم مبحث پیچیده ای هست
مثلا در فایل Legacy  این موارد چی هستن؟

[System.Windows.Threading.Dispatcher]::Invoke
[System.Windows.Threading.Dispatcher]::InvokeAsync
[System.Windows.Threading.Dispatcher]::BeginInvoke
[System.Threading.SynchronizationContext]::Send
[System.Threading.SynchronizationContext]::Post

و فایل Switch
[Microsoft.VisualStudio.Threading.JoinableTaskFactory]::SwitchToMainThreadAsync

این موارد چه چیزی میخواهد به من بگوید؟

**Comment by codehaks** [comment]
مثلا اگر در کد متد Invoke در کتابخانه System.Windows.Threading.Dispatcher  استفاده کرده باشید به شما Warning میده که این روش قدیمی شده و بهتره کد رو عوض کنید. شما می توانید این موارد رو کم یا زیاد کنید.
