### ISSUE TITLE
رفرنس شدن PropertyGroup

### ISSUE THREAD

**Issue by fakhravari** [codehaks/BookShop#4]
با سلام
چطوری میشه این 2 مشخصه سلوشن ها به صورت کلی مثل پراپرتی های  Directory.Build.props تعریف کرد 

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

و سرعت بیلد شدن سلوشن پاین اومده دلیلش چی میتونه باشد؟

**Comment by codehaks** [comment]
کافیه هر کدوم رو به فایل Build.Props منتقل کنید. اگر لازم بود این تنظیمات برای یک پروژه خاص تغییر بکنه به csproj همون پروژه اضافه کنید و میتونید مقادیر Build رو Override کنید.

**Comment by codehaks** [comment]
سرعت پایین اومده چون آنالیز کننده های زیادی به پروژه اضافه شده که هر تغییر شما رو چک میکنه می تونید آنالیزور ها رو غیر فعال کنید :

```xml
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
```
